### ISSUE TITLE
Reference to FDR function

### ISSUE THREAD

**Issue by marizurita** [henkcremers/Simulate-Sampling-fMRI#1]
Hello!

Thank you very much for the code. I was trying to run a simulation, but stumbled with the following issue: on line 63 of the file Simulate-Sampling-fMRI/simsam_samplestats.m, you try to use a FDR function:

```matlab
thrFDR = FDR(pval,0.05);
```

 However, I cannot find that function. Which one is it?

Thank you very much!

**Comment by henkcremers** [comment]
Hello, 

Sorry for the (extremely) late reply, here is a link to the code: https://warwick.ac.uk/fac/sci/statistics/staff/academic-research/nichols/software/fdr/

Best,
Henk
